# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: AIODrive Trajectory Forecasting Challenge
short_description: Trajectory forecasting with complext multi-agent interactions using the AIODrive dataset
description: templates/description.html                     # done
evaluation_details: templates/evaluation_details.html       # done
terms_and_conditions: templates/terms_and_conditions.html   # done
image: logo.png
submission_guidelines: templates/submission_guidelines.html # done
leaderboard_description: Empty
evaluation_script: evaluation_script/main.py
remote_evaluation: False
is_docker_based: False
start_date: 2019-01-01 00:00:00
end_date: 2099-05-31 23:59:59
published: True
allowed_email_domains: []
blocked_emails_domains: []

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["ADE_20", "FDE_20", "APD_20", "FPD_20", "MsR_20"],
        "default_order_by": "ADE_20",
      }

challenge_phases:
  - id: 1
    name: Validation Phase
    description: templates/challenge_phase_1_description.html   # done
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2019-01-19 00:00:00
    end_date: 2099-04-25 23:59:59
    test_annotation_file: annotations/aiodrive_traj_val.json
    codename: val
    max_submissions_per_day: 30
    max_submissions_per_month: 1000
    max_submissions: 10000
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: True
    allowed_submission_file_types: ".json"
  - id: 2
    name: Test Phase
    description: templates/challenge_phase_2_description.html   # done
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2019-01-01 00:00:00
    end_date: 2099-05-24 23:59:59
    test_annotation_file: annotations/aiodrive_traj_test.json
    codename: test
    max_submissions_per_day: 3
    max_submissions_per_month: 10
    max_submissions: 30
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: True
    allowed_submission_file_types: ".json"

dataset_splits:
  - id: 1
    name: Val Split
    codename: val_split
  - id: 2
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 3
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 2
    visibility: 3
    leaderboard_decimal_precision: 3
    is_leaderboard_order_descending: True